[build]
  command = "npm run build"
  publish = ".next"

  [build.environment]
    NODE_VERSION = "18"
    NETLIFY_USE_YARN_CACHE = "false"
    NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
